### ISSUE TITLE
VQA: Remove breadcrumbs from product category pages

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-shop#1]
The store doesn’t appear to be very deep, so I think we can remove the breadcrumbs that appear on product category pages. 

If that causes problems for some reason, can we move the breadcrumbs above the “Product categories” heading, so they’re right below the orange header? The current placement feels off hierarchically. 

![image](https://user-images.githubusercontent.com/6118778/40382237-e807070a-5dcb-11e8-8f5f-8fda330edbe3.png)

**Comment by Henryhankdc** [comment]
@jamielyn bread crumbs have been removed.

**Comment by jamielyn** [comment]
:cat:
