### ISSUE TITLE
VQA: Change color of mini cart text 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-shop#2]
There’s insufficient contrast in the mini cart list with white text on a light gray background. Please change the color of the text to #493d30

![image](https://user-images.githubusercontent.com/6118778/40382310-177a1144-5dcc-11e8-9245-64e5fb4b28eb.png)

**Comment by Henryhankdc** [comment]
@jamielyn this color was also tied to the header/footer color change.

![minicart-dropdown](https://user-images.githubusercontent.com/10802697/40446317-d1d3f8a4-5e9c-11e8-8999-b12e7a8877a0.png)

Please advise if this text color should still be changed to #493d30

**Comment by jamielyn** [comment]
@Henryhankdc 

- Please change the background of the mini cart to brown #493d30
- Change the Checkout button to orange #d47500 
- Make View Cart a ghost button with a 2px orange #d47500 border 

![screen shot 2018-05-23 at 4 28 34 pm](https://user-images.githubusercontent.com/6118778/40450499-e5d987d0-5ea9-11e8-9645-81073795d87e.png)

**Comment by jamielyn** [comment]
@Henryhankdc This looks great! It looks like we lost the hover states on the buttons though.  

For the checkout button, let's use the same hover state as the Add to Cart buttons on the products: #bb5c00

And can we make the View Cart button fill in with orange on hover? ##d47500

**Comment by Henryhankdc** [comment]
@jamielyn I forgot to mention the cache may be sticky on this site. I cleared the cache on pantheon. If you are not seeing the button styles try a hard refresh on your browser.

**Comment by jamielyn** [comment]
:horse:
