### ISSUE TITLE
VQA: Mobile - Change color of menu button label

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-shop#3]
There’s insufficient contrast with white text on a light gray background. Please change the color of the text to #493d30

![image](https://user-images.githubusercontent.com/6118778/40382351-2e602a06-5dcc-11e8-9790-f23ad2ab05b7.png)

**Comment by Henryhankdc** [comment]
@jamielyn in the process of resolving the footer color issue I discovered that color styles in this woocommerce this for header and footer are tied together. This also effects the mobile menu button. The buttons now appears with the background color of #d47500. 

![aldf-shop-mobile-menu-button](https://user-images.githubusercontent.com/10802697/40443123-53b008cc-5e93-11e8-84ff-f6a9e9932626.png)

With this new view, let me know if you want me to keep the color as is or change it to #493d39 as originally requested.

**Comment by jamielyn** [comment]
@Henryhankdc Please change the mobile menu button to brown #493d30. Let's remove the white border as well. Thanks!

**Comment by Henryhankdc** [comment]
color has been changed and white border has been removed.

**Comment by jamielyn** [comment]
:koala:
