### ISSUE TITLE
VQA: Mobile - Sticky footer adjustments 

### ISSUE THREAD

**Issue by jamielyn** [Threespot/aldf-shop#4]
Let’s make the background orange, so the white icon links are visible. @lfhello feel free to weigh in if you'd like a different color. 

There are two user icons, but one links to aldf.org and the other to the my account page. On desktop, the aldf link is in the brown footer. 

![image](https://user-images.githubusercontent.com/6118778/40382419-6d072084-5dcc-11e8-9e2e-b0fd6b5ed713.png)

**Comment by lfhello** [comment]
Yes, let's make the background the orange #D47500

**Comment by jamielyn** [comment]
@Henryhankdc Please change the mobile footer background to brown #493d30

**Comment by Henryhankdc** [comment]
color has been changed to #493d30

**Comment by lfhello** [comment]
@Henryhankdc the brown is MUCH better! Thank you.

**Comment by jamielyn** [comment]
:bear:
